version: '3.8'

services:
    # app:
    #   image: node:18.20.4
    #   container_name: foodie_app
    #   environment:
    #     - DB_HOST=db
    #     - DB_PORT=${DB_PORT}
    #     - DB_USERNAME=${DB_USERNAME}
    #     - DB_PASSWORD=${DB_PASSWORD}
    #     - DB_DATABASE=${DB_DATABASE}
    #     - JWT_SECRET=${JWT_SECRET}
    #   depends_on:
    #     - db
    #   networks:
    #     - foodie_network

    db:
        image: postgres:14
        container_name: foodie_db
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
        ports:
            - '${DB_PORT}:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - foodie_network

networks:
    foodie_network:
        driver: bridge

volumes:
    postgres_data:
